In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("intro2LinAlg.ipynb")

## Lecture Section

In this lecture, we will cover some linear algebra basics.
We will cover:
* Vectors
    * Operations
    * Linear Combinations
* Matrices
    * Operations
    * Vector-matrix Operations
* Solving Equations
* Norms
* Condition Number

## Vectors

In [2]:
import numpy as np
from numpy import linalg as la

### Creating Vectors

We can make vectors in a lot of different ways. The simplest is to use:

In [3]:
v1 = np.array([1, 2, 3, 4])
v1

array([1, 2, 3, 4])

We can also use `np.repeat()`, which repeats the first argument's number the second argument's number of times.

In [4]:
v2 = np.repeat(7, 4)
v2

array([7, 7, 7, 7])

Maybe we want some sort of sequence:

In [5]:
v3 = np.arange(0, 101, 10)
v3

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Vectors can have any type of number in them. If one number is a decimal, the rest are converted to decimal.

In [6]:
v4 = np.array([-5, 0.23, 1, 2849, -32.91])
v4

array([-5.000e+00,  2.300e-01,  1.000e+00,  2.849e+03, -3.291e+01])

This is true if the decimals are 0, too.

Note: this is different from R!

In [7]:
v5 = np.array([-5, 0.00, 1, 2849, -32.00])
v5

array([-5.000e+00,  0.000e+00,  1.000e+00,  2.849e+03, -3.200e+01])

### Vector Operations

We can assign new numbers to our vectors by indexing (note: Python uses 0-based indexing):

In [8]:
v4[2] = 7
v4

array([-5.000e+00,  2.300e-01,  7.000e+00,  2.849e+03, -3.291e+01])

We can add two vectors of the same length together. Using the `+` operator adds the numbers at the corresponding indices.

In [9]:
print(v1)
print(v2)
v1 + v2

[1 2 3 4]
[7 7 7 7]


array([ 8,  9, 10, 11])

We can multiply by a scalar, too. The scaler is multiple to each value.

In [10]:
3 * v1

array([ 3,  6,  9, 12])

We can multiply element-wise by another vector of the same size.

In [11]:
v1 * v2

array([ 7, 14, 21, 28])

We can also calculate the inner product, which is the sum of the element-wise multiplication.

In [12]:
np.dot(v1, v2)

np.int64(70)

We can still add and multiply if the lengths are different - but the smaller vector will repeat to become the same length as the larger vector (broadcasting). Broadcasting is not as nice as it is in R - it is not automatic in Python, and we cannot broadcast if the size of the smaller array is not a factor of the larger array. We can use `.tile()` to help us. Otherwise, we get an error.

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([9, 8, 7])
z = np.array([3, 6, 2, 1])


x * np.tile(y, len(x) // len(y))

array([ 9, 16, 21, 36, 40, 42])

In [14]:
x + np.tile(y, len(x) // len(y))

array([10, 10, 10, 13, 13, 13])

In [17]:
 #x + y # error

In [ ]:
# x + np.tile(z, len(x) // len(z)) # error

### Linear Combinations

A linear combination is when we add two or more vectors with scalar coefficients together.

In [18]:
x = np.array([1, 2, 3])
y = np.array([9, 8, 7])
a = 2
b = -1

# linear combination
a*x + b*y

array([-7, -4, -1])

A set of vectors is linearly independent if the only way to create linear combinations equal to 0 is to have the coefficients all equal to 0. In other words, no vector can be written as the combination of another.

In [19]:
# Linearly Independent
v1 = np.array([1, 0])
v2 = np.array([0, 1])

In [20]:
# Not Linearly Independent
v1 = np.array([2, 4])
v2 = np.array([4, 8])

2*v1 + (-1)*v2

array([0, 0])

Finally, we can convert vectors into column vectors.

In [21]:
v1

array([2, 4])

In [22]:
v1.reshape(-1, 1)

array([[2],
       [4]])

## Matrices

### Creating Matrices

There are several ways to make matrices. Here are 4 common ways:

In [23]:
# byrow=FALSE equivalent: fill column by column
A = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3, order='F')
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
# byrow=TRUE equivalent: fill row by row (C order)
B = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3, order='C')
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

This is also the default

In [25]:
B = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# cbind equivalent: stack column arrays horizontally
C = np.column_stack(([1,2,3], [4,5,6], [7,8,9]))
C

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
# rbind equivalent: stack row arrays vertically
D = np.vstack(([1,2,3], [4,5,6], [7,8,9]))
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

This is also a default option

In [28]:
D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`.array()` is more flexible than `.matrix()`. `.matrix()` may be deprecated in the future, so we will not use it.

### Matrix Operations

We can multiply or add a matrix with another matrix. We can either do an element-by-element multiplication, or a matrix multiplication. The first matrix's number of columns should match the second matrix's number of rows for matrix multiplication. For element-by-element or addition, we want the same number of rows and columns.

In [29]:
A = np.array([[4, 2], [0, 1]])
B = np.array([[1, 7], [0, 6]])
print("A:\n", A)
print("B:\n", B)
print("Element-wise A*B:\n", A * B)

A:
 [[4 2]
 [0 1]]
B:
 [[1 7]
 [0 6]]
Element-wise A*B:
 [[ 4 14]
 [ 0  6]]


In [31]:
# Matrix multiplication
A @ B

array([[ 4, 40],
       [ 0,  6]])

In [32]:
A + B

array([[5, 9],
       [0, 7]])

We can transpose a matrix, switching its columns and rows:

In [33]:
print(D)
print(D.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
col_vec = np.array([[1], [2]])
print(col_vec)
print(col_vec.T)
print(col_vec.T.T)

[[1]
 [2]]
[[1 2]]
[[1]
 [2]]


We can invert a matrix with a simple function call. If the inverse does not exist, it will give an error.

In [35]:
A = np.array([[1, 2], [-1, 2]])
inv = la.inv(A)
inv

array([[ 0.5 , -0.5 ],
       [ 0.25,  0.25]])

When multiplying the matrix by its inverse, we get its identity matrix.

In [36]:
inv @ A

array([[1., 0.],
       [0., 1.]])

At times, we might need the determinant of a matrix. This is a scalar value found by some simple algebra within the matrix - it can tell us things about the matrix. I won't cover them now; I will just show you how to find it.

### Vector-Matrix Operations

We can multiply a matrix by a vector as long as the number of columns in the matrix match the number of rows in the vector.

In [37]:
B = np.array([[1, 2], [3, 4], [5, 6]])
x = np.array([[3], [5]])
print("B:\n", B)
print("x:\n", x)
print("B @ x:\n", B @ x)

B:
 [[1 2]
 [3 4]
 [5 6]]
x:
 [[3]
 [5]]
B @ x:
 [[13]
 [29]
 [45]]


In [38]:
A = np.array([[1, 2], [-1, 2]])
la.det(A)

np.float64(4.0)

## Solving Equations

To solve a system of equations Ax = b, you can use:

```python
x = np.linalg.solve(A, b)
```

For example:

In [39]:
# solve
# 3x + 2y - 4z = 2
# x - 2y + 2z = 4
# -5x + y + z = 12

A = np.array([[3, 2, -4],
              [1, -2, 2],
              [-5, 1, 1]])
b = np.array([2, 4, 12])

print("A:\n", A)
print("b:", b)
print("Solution:", la.solve(A, b))

A:
 [[ 3  2 -4]
 [ 1 -2  2]
 [-5  1  1]]
b: [ 2  4 12]
Solution: [ -40. -105.  -83.]


This was the original motivation for linear algebra. However, it leaves the question of whether a unique solution exists or not.
We can use the rank of A (the number of linearly independent row vectors). If it equals n, a unique solution exists.
We can find the rank using `np.linalg.matrix_rank()` or via SVD decomposition.

In [40]:
# Using matrix_rank directly
rank_A = la.matrix_rank(A)
print("Rank (matrix_rank):", rank_A)

# Using SVD decomposition
svd_values = la.svd(A, compute_uv=False)
rank_A = np.sum(svd_values > 1e-10)
print("Rank (SVD):", rank_A)

Rank (matrix_rank): 3
Rank (SVD): 3


## Norms

### Vectors

L1 norm is the taxicab norm, or the sum of absolute values.

In [41]:
x = np.array([3, -1, 4, -9, 7])
L1_manual = sum(abs(x))
L1 = la.norm(x, 1)
print(L1)
print(L1_manual)

24.0
24


The L2 norm is the Euclidean distance.

In [42]:
L2_manual = np.sqrt(np.sum(x**2))
L2 = la.norm(x, 2)
print(L2_manual)
print(L2)

12.489995996796797
12.489995996796797


A unit vector has an L2 norm of 1.

### Matrix Norms

There are three main norms for a matrix:

L1 measures the largest column sum (using absolute values).

In [43]:
A = np.column_stack(([3,1,-5], [2,-2,1], [-4,2,1]))
la.norm(A, 1)

np.float64(9.0)

L2 measures the largest singular value of A (maximum gain or amplification of x).

In [44]:
la.norm(A, 2)

np.float64(6.7319721179492715)

Frobenius treats the matrix like a long list of numbers and computes the Euclidean length.

In [45]:
la.norm(A, 'fro')

np.float64(8.06225774829855)

We won't cover the equations of these, or how to do them by hand. There are better suited classes for that.

## Condition Number

When we talk about matrices, such as the Matrix A, we care about what this matrix can do to some "input", or x. The input vector x is the starting point that we apply A to, and we get Ax as a result. When you apply the matrix A to all unit vectors, Ax traces out an ellipse. The norm of A is the length of the longest semi-major axis of this ellipse.

A condition number of a matrix A is the norm * inverse(norm). This number tells you how much a matrix "distorts" space - or, how sensitive A is to input errors. If the condition is large, the matrix is unstable, and the input vector having small amounts of error (like rounding errors, for example), will make calculations unstable.

In [46]:
A = np.array([[1, 2], [3, 4]])
print("A:\n", A)

# Manual condition number: norm(A) * norm(A_inv)
manual_cond = la.norm(A, 2) * la.norm(la.inv(A), 2)
print("Manual condition number:", manual_cond)

print("np.linalg.cond:", la.cond(A))

A:
 [[1 2]
 [3 4]]
Manual condition number: 14.93303437365925
np.linalg.cond: 14.933034373659268


## Assignment Section

**Question 1.**
Given the vectors below, compute the following and store your results in the given variable names:

- `dot_product`: the inner product of `u` and `v`
- `linear_combo`: the linear combination $3u - 2v$
- `u_unit`: the unit vector of `u` (i.e., normalize `u` to have an L2 norm of 1)

In [47]:
from numpy import linalg as la

u = np.array([2, -1, 4])
v = np.array([3, 5, -2])
dot_product = np.dot(u,v)
linear_combo = 3*u - 2*v
u_unit = u/la.norm(u,2)

In [48]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2.**
Given matrix `A` below:

- `A_inv`: compute the inverse of `A`
- `A_det`: compute the determinant of `A`
- `A_transpose`: compute the transpose of `A`

In [49]:
import numpy as np
from numpy import linalg as la
A = np.array([[2, 1],
              [5, 3]])
A_inv = la.inv(A)
A_det = la.det(A)
A_transpose = A.T

In [50]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3.**

Solve the following system of equations and answer the questions below:

$$2x + y - z = 8$$
$$-3x - y + 2z = -11$$
$$-2x + y + 2z = -3$$

- `solution`: a numpy array containing the solution $[x, y, z]$ using `np.linalg.solve()`
- `rank_C`: the rank of the coefficient matrix `C` (as an integer)
- `has_unique_solution`: a boolean — `True` if a unique solution exists, `False` otherwise
- `frobenius_norm`: the Frobenius norm of `C`

In [52]:
from numpy import linalg as la
C = np.array([[ 2,  1, -1],
              [-3, -1,  2],
              [-2,  1,  2]])
b = np.array([8, -11, -3])

solution = np.linalg.solve(C,b)
rank_C = la.matrix_rank(C)
has_unique_solution = rank_C == 3
frobenius_norm = la.norm(C,'fro')

In [53]:
grader.check("q3")

q3 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [54]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!